/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

// name is set in settings.gradle.kts lol
group = "dev.qixils.cc4j"
version = "1.1.0"

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.vanniktech.maven.publish") version "0.34.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    annotationProcessor(libs.record.builder.processor)
    compileOnly(libs.record.builder.core)
    implementation(libs.jackson.core)
    implementation(libs.jackson.annotations)
    implementation(libs.jackson.databind)
    implementation(libs.slf4j)
    api(libs.geantyref)
    api(libs.annotations)
}

// java version
val targetJavaVersion = 21
tasks.withType<JavaCompile>().configureEach {
    options.release.set(targetJavaVersion)
    options.encoding = Charsets.UTF_8.name()
}
java {
    val javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion.set(JavaLanguageVersion.of(targetJavaVersion))
    }
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

mavenPublishing {
    publishToMavenCentral(automaticRelease = true)
    signAllPublications()

    coordinates(groupId = "dev.qixils", artifactId = "cc4j-pubsub")

    pom {
        name.set("crowdcontrol4j pubsub")
        description.set("An implementation of the Crowd Control PubSub WebSocket protocol for Java 21+")
        inceptionYear.set("2024")
        url.set("http://github.com/qixils/crowdcontrol4j-pubsub")
        licenses {
            license {
                name.set("Functional Source License, Version 1.1, Apache 2.0 Future License")
                url.set("https://github.com/qixils/crowdcontrol4j-pubsub/blob/main/LICENSE.md")
                distribution.set("https://github.com/qixils/crowdcontrol4j-pubsub/blob/main/LICENSE.md")
            }
        }
        developers {
            developer {
                id.set("qixils")
                name.set("Lexi Larkin")
                url.set("https://github.com/qixils/")
            }
        }
        scm {
            url.set("http://github.com/qixils/crowdcontrol4j-pubsub/")
            connection.set("scm:git:git://github.com/qixils/crowdcontrol4j-pubsub.git")
            developerConnection.set("scm:git:git://github.com/qixils/crowdcontrol4j-pubsub.git")
        }
    }
}
